name: Build Bluefin LTS (full)

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Build Bluefin LTS"
      - "Build Bluefin LTS DX"
      - "Build Bluefin LTS DX HWE"
      - "Build Bluefin LTS HWE"
      - "Build Bluefin LTS GDX"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
